// Auto-generated by extract_data.py — do not edit manually

export const roa = 0.02069939300383274;
export const wacc = 0.11375006614277033;

export interface Project {
  name: string;
  vpn: number;
  inversion: number;
  selected: boolean;
}

export const projects: Project[] = [
  { name: "A", vpn: 23629095.23352544, inversion: -80000000.0, selected: false },
  { name: "B", vpn: 45624142.66117969, inversion: -60000000.0, selected: false },
  { name: "C", vpn: 54750273.31350045, inversion: -60000000.0, selected: true },
  { name: "D", vpn: 55553880.863538936, inversion: -40000000.0, selected: true },
];

export const vpnTotal = 110304154.17703938;
export const inversionUtilizada = 100000000.0;

export const razonCorriente = 2.9817153455207137;
export const rotacionCartera = 281.7508038340701;
export const coberturaIntereses = 0.8719258357712559;

export interface FclEntry { year: number; value: number; }
export const fclProyecciones: FclEntry[] = [
  { year: 2016, value: -674573.6708750026 },
  { year: 2017, value: -5670464.661624998 },
  { year: 2018, value: 952230.1397124976 },
  { year: 2019, value: -5679843.195610495 },
  { year: 2020, value: 2112079.2628839742 },
  { year: 2021, value: 2525840.1659284974 },
  { year: 2022, value: 2589735.3709063465 },
  { year: 2023, value: 2655547.4320335435 },
  { year: 2024, value: -5276666.145005449 },
  { year: 2025, value: 3057153.8706443794 },
];

export const valorTerminal = 37598399.99882239;
export const vpValorTerminal = 12802416.01600059;
